
image: node:6.10.0

variables:
  #UNITY_BRANCH: "trunk"
  #UNITY_TEST_PROJECT: ".\\TestProjects\\SampleProject1"
  BINTRAY_STAGING: "https://staging-packages.unity.com"

before_script:
  - chmod +x build.sh

stages:
 - test
 - publish

test:windows:2019-1:
  stage: test
  image: 'build-pipeline/addressables_win:stable'
  dependencies:
    - create_package:windows
  artifacts:
    paths:
      - "TestArtifacts"
    expire_in: 1 week
    when: always
  tags:
   - bokken-runner
  script:
    - echo "Running Android Playmode Tests"
    - python.exe -u testrunner.py Android --version=2019.1
  before_script:
    - mkdir C:\ProgramData\Unity
    - wget -P C:\ProgramData\Unity\ http://172.28.214.140/upload/licence/Unity_lic.ulf

publish:
  stage: publish
  only:
  - master
  - tags
  script:
    - ./build.sh npm auth "$BINTRAY_STAGING" "$USER_NAME" "$API_KEY"
    - ./build.sh package-ci publish --git-head $CI_COMMIT_SHA --git-url $CI_REPOSITORY_URL



  
