
image: node:6.10.0

variables:
  #UNITY_BRANCH: "trunk"
  #UNITY_TEST_PROJECT: ".\\TestProjects\\SampleProject1"
  BINTRAY_STAGING: "https://staging-packages.unity.com"

before_script:
  - chmod +x build.sh

stages:
 - verify
 - test
 - publish
 
verify:format:
 image: ubuntu:18.10
 stage: verify
 script:
 - apt-get update && apt-get install -y perl mercurial
 - echo -e "[extensions]\nlargefiles=\n" > ~/.hgrc
 - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
 - hg clone -u stable https://$GITLAB_UNITY_META_ONO_USER@ono.unity3d.com/unity-extra/unity-meta ~/unity-meta
 # for optimization purposes we can do a first optional pass with the generic formatter which will fail faster if code is not compliant with generic format rules
 - perl ~/unity-meta/Tools/Format/format.pl --hgroot $(pwd) --dry-run --generic-only com.unity.mobile.android-logcat/Editor com.unity.mobile.android-logcat/Tests/Editor TestProjects
 # full format (will invoke dedicated formatters)
 - perl ~/unity-meta/Tools/Format/format.pl --hgroot $(pwd) --dry-run com.unity.mobile.android-logcat/Editor com.unity.mobile.android-logcat/Tests/Editor TestProjects


test:windows:2019-1:
  stage: test
  image: 'core-meta/harisen-base-image:stable'
  artifacts:
    paths:
      - "TestArtifacts/*"
    expire_in: 1 week
    when: always
  tags:
   - bokken-runner
  script:
    - echo "Running Android Playmode Tests"
    - python.exe -u testrunner.py Android --version=2019.1
    
publish:
  stage: publish
  only:
  - tags
  script:
    - ./build.sh npm auth "$BINTRAY_STAGING" "$USER_NAME" "$API_KEY"
    - ./build.sh package-ci publish --git-head $CI_COMMIT_SHA --git-url $CI_REPOSITORY_URL



  
