variables:
  UNITY_BRANCH: "trunk"

stages:
 - build

build:
  stage: build
  tags:
      - windows
	  - buildfarm
  only:
      - master
  script:
      - python .\GitlabCI\gitlabCI.py -u
  # Important! Do not remove this after_script as the VM will live for 12 hours before being destroyed! https://gitlab.internal.unity3d.com/CDS_Ops/buildfarm-runners
  after_script:
    - C:\Users\builduser\post_build_script.bat



  
