
image: node:6.10.0

variables:
  #UNITY_BRANCH: "trunk"
  #UNITY_TEST_PROJECT: ".\\TestProjects\\SampleProject1"
  BINTRAY_STAGING: "https://staging-packages.unity.com"

before_script:
  - chmod +x build.sh

stages:
 - test
 - publish

test:windows:2019-1:
  stage: test
  image: 'toolsmith/katana-bokken-image:stable'
  artifacts:
    paths:
      - "TestArtifacts"
      - "UnityInstall"
    expire_in: 1 week
    when: always
  tags:
   - bokken-runner
  script:
    - echo "Running Android Playmode Tests"
    - python.exe -u testrunner.py Android --version=2019.1

publish:
  stage: publish
  only:
  - master
  - tags
  script:
    - ./build.sh npm auth "$BINTRAY_STAGING" "$USER_NAME" "$API_KEY"
    - ./build.sh package-ci publish --git-head $CI_COMMIT_SHA --git-url $CI_REPOSITORY_URL



  
